[tool.poetry]
name = "high-level-synthesis-dataset"
version = "0.1.0"
description = "high-level-synthesis-dataset"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.13"
pandas = "*"
matplotlib = "*"
jupyterlab = "*"
wget = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
